// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:221608649944:web:ac46df2f6352798dbaa3ad',
    messagingSenderId: '221608649944',
    projectId: 'myapp-c440b',
    authDomain: 'myapp-c440b.firebaseapp.com',
    storageBucket: 'myapp-c440b.firebasestorage.app',
    measurementId: 'G-5JKD5LRNFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:221608649944:android:09afcec5042de28cbaa3ad',
    messagingSenderId: '221608649944',
    projectId: 'myapp-c440b',
    storageBucket: 'myapp-c440b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:221608649944:ios:8e4219b44e3efa4dbaa3ad',
    messagingSenderId: '221608649944',
    projectId: 'myapp-c440b',
    storageBucket: 'myapp-c440b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:221608649944:ios:8e4219b44e3efa4dbaa3ad',
    messagingSenderId: '221608649944',
    projectId: 'myapp-c440b',
    storageBucket: 'myapp-c440b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_API_KEY',
    appId: '1:221608649944:web:da5ccb7bd1664049baa3ad',
    messagingSenderId: '221608649944',
    projectId: 'myapp-c440b',
    authDomain: 'myapp-c440b.firebaseapp.com',
    storageBucket: 'myapp-c440b.firebasestorage.app',
    measurementId: 'G-5BFVDEFT0K',
  );
}
